# Generated by Django 6.0.4 on 2026-04-13 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('faculty', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('computer_science', 'Computer Science'), ('business_admin', 'Business Administration'), ('medicine', 'Medicine & Health Sciences'), ('law', 'Law'), ('natural_sciences', 'Natural Sciences'), ('social_sciences', 'Social Sciences'), ('arts_humanities', 'Arts & Humanities')], max_length=30)),
                ('location', models.CharField(blank=True, choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('central', 'Central'), ('eastern', 'Eastern'), ('northern', 'Northern'), ('volta', 'Volta'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('bono', 'Bono')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_online', models.BooleanField(default=True)),
                ('is_active_account', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('campus', 'Campus Only'), ('everyone', 'Everyone'), ('private', 'Private')], default='campus', max_length=10)),
                ('preferred_meetup', models.CharField(choices=[('library', 'Library Foyer'), ('student_union', 'Student Union'), ('main_gate', 'Main Gate'), ('cafeteria', 'Cafeteria')], default='library', max_length=20)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_orders', models.BooleanField(default=True)),
                ('notify_price_drops', models.BooleanField(default=True)),
                ('notify_promos', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=True)),
                ('username_change_count', models.PositiveSmallIntegerField(default=0)),
                ('username_last_changed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
