from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
import json
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Listing
#from . import Listing
# Create your views here.


@login_required(login_url='auth:auth_view')

def listings(request):
    """
    My Listings Page
    GET /listings/listings/
    
    Displays:
    - User's active listings
    - Listing management options
    - Create new listing button
    - Listing performance metrics
    """
    context = {
        'page_title': 'My Listings - PU-Marketplace',
        'page_description': 'Manage your product and service listings.',
        # Add any additional context data needed for the listings page here
    }
    return render(request, 'listings/listings.html', context)


@login_required(login_url='auth:auth_view')
def wishlist(request):
    """
    Wishlist Page
    GET /listings/wishlist/
    
    Displays:
    - Saved favorite items
    - Wishlist management options
    - Item details and prices
    - Option to move items to cart or remove from wishlist
    """
    context = {
        'page_title': 'Wishlist - PU-Marketplace',
        'page_description': 'View and manage your saved favorite items.',
        # Add any additional context data needed for the wishlist page here
    }
    return render(request, 'listings/wishlist.html', context)


@login_required(login_url='auth:auth_view')
def create_listing(request):
    """
    Create Listing Page
    GET /listings/create/
    
    Displays:
    - Listing creation form
    - Product/service details form
    - Photo upload
    - Pricing form
    """
    context = {
        'page_title': 'Create New Listing - PU-Marketplace',
        'page_description': 'Post a new item or service.',
    }
    return render(request, 'listings/create-listing.html', context)




@login_required
@require_POST
def create_listing_api(request):
    """
    Finalizes the 5-step process by saving the text data 
    and the Cloudinary URL string to the database.
    """
    try:
        # Parse the JSON data sent from the frontend
        data = json.loads(request.body)
        
        # Extract fields matching your 5-step form logic
        title = data.get('title')
        price = data.get('price')
        description = data.get('description')
        category = data.get('category')
        condition = data.get('condition')
        # This is the URL string generated by the frontend Cloudinary upload
        image_url = data.get('image_url')

        # Basic validation
        if not all([title, price, image_url]):
            return JsonResponse({'status': 'error', 'message': 'Missing required fields'}, status=400)

        # Create the database entry
        new_listing = Listing.objects.create(
            user=request.user,
            title=title,
            price=price,
            description=description,
            category=category,
            condition=condition,
            image_url=image_url,
            
        )

        return JsonResponse({
            'status': 'success',
            'message': 'Listing created successfully!',
            'listing_id': new_listing.id
        })

    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    

@login_required
def get_my_listings(request):
    """
    Fetches listings for the logged-in user to display in the UI.
    """
    # Fetch user's listings, newest first
    listings = Listing.objects.filter(user=request.user).order_by('-created_at')
    
    # Format data for the frontend
    listings_data = []
    for item in listings:
        listings_data.append({
            'id': item.id,
            'title': item.title,
            'price': str(item.price), # Decimal to string for JSON
            'image': item.image_url,  # The direct Cloudinary "pull" link
            'category': item.category,
            'condition': item.condition,
            'status': 'Available' if item.is_available else 'Sold',
            'date': item.created_at.strftime('%d %b, %Y')
        })
    
    return JsonResponse({'listings': listings_data})